## src/tests/TrainTests/BUILD

cc_library(
    name = "TrainTests",
    srcs = ["TrainTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Train:Train",
    ]
)
