## src/tests/ListTests/BUILD

cc_library(
    name = "ListTests",
    srcs = ["ListTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/List:List",
    ]
)
