## src/tests/MyStringTests/BUILD

cc_library(
    name = "MyStringTests",
    srcs = ["MyStringTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/MyString:MyString",
    ]
)
