## src/tests/StudentTests/BUILD

cc_library(
    name = "StudentTests",
    srcs = ["StudentTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Student:Student",
    ]
)
