## src/TreeContainer/BUILD

cc_library(
    name = "TreeContainer",
    srcs = ["TreeContainer.cpp"],
    hdrs = ["TreeContainer.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Tree:Tree",
        "//src/ForestTree:ForestTree",
        "//src/FruitTree:FruitTree",
    ],
)
