## src/tests/BusTests/BUILD

cc_library(
    name = "BusTests",
    srcs = ["BusTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Bus:Bus",
    ]
)
