## src/tests/TreeTests/BUILD

cc_library(
    name = "TreeTests",
    srcs = ["TreeTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Tree:Tree",
    ]
)
