## src/tests/PersonTests/BUILD

cc_library(
    name = "PersonTests",
    srcs = ["PersonTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Person:Person",
    ]
)
